-- Auto-generated by scripts/stoberscript/generate_speechstyle_bio_random.py
BEGIN;
DELETE FROM bio_random
WHERE LOWER(type) = 'speechstyle'
  AND COALESCE(name, '') = ''
  AND COALESCE(race, '') = ''
  AND COALESCE(gender, '') = ''
  AND COALESCE(faction, '') = '';

WITH source_rows(description) AS (
    VALUES
        ('Uses plain, workmanlike wording, usually putting the main point in the first sentence. Questions are usually framed to get a useful answer rather than invite reflection.'),
        ('Uses careful wording that tries to mark the limits of each claim, often adding conditions before the main conclusion. Questions are often used to test assumptions before a full answer is offered.'),
        ('Uses more formal wording than the situation strictly requires, often naming the premise before the judgment. Even ordinary remarks arrive with a little more structure than casual talk usually carries.'),
        ('Uses friendly, everyday phrasing without getting sloppy, usually starting from a shared practical point before narrowing into detail. The wording stays readable because detail is introduced in everyday terms first.'),
        ('Keeps the language stripped down and practical, usually putting the main point in the first sentence. When emphasis is needed, they rely on clearer wording instead of stronger ornament.'),
        ('Builds sentences with caution around certainty, often adding conditions before the main conclusion. They sound most comfortable when distinctions are named directly instead of implied.'),
        ('Prefers polished phrasing with a clear internal structure, often naming the premise before the judgment. The result is language that sounds organized without relying on dramatic wording.'),
        ('Builds sentences that feel informal but still organized, usually starting from a shared practical point before narrowing into detail. Requests feel collaborative because the sentence often includes the reason for them.'),
        ('Prefers direct statements over decorative phrasing, usually putting the main point in the first sentence. The wording stays literal enough that most listeners know what action is being asked for.'),
        ('Prefers qualified phrasing over hard absolutes, often adding conditions before the main conclusion. They prefer to revise a sentence mid-thought rather than let an overbroad version stand.'),
        ('Builds sentences with deliberate order and explicit transitions, often naming the premise before the judgment. The style is easier to follow because the connective logic is usually stated outright.'),
        ('Prefers language that sounds accessible and unforced, usually starting from a shared practical point before narrowing into detail. Statements stay open enough to invite response without becoming vague.'),
        ('Frames ideas with conditions before commitment, often adding conditions before the main conclusion. Sentences can run a little longer because they carry the limits of the argument with them.'),
        ('Leans toward exact, orderly language, often naming the premise before the judgment. Questions tend to be fully formed and specific about what answer is being asked for.'),
        ('Keeps wording relaxed while still moving toward a point, usually starting from a shared practical point before narrowing into detail. Questions are usually framed to keep the exchange moving instead of stopping it cold.'),
        ('Leans on ordinary, concrete words instead of flourish, usually putting the main point in the first sentence. The result is spare language that favors clarity over charm.'),
        ('Chooses language that leaves room for exception, often adding conditions before the main conclusion. The wording stays cautious without collapsing into vagueness.'),
        ('Favors complete statements over fragments or shorthand, often naming the premise before the judgment. When disagreement appears, it is usually framed as a reasoned distinction rather than a sharp interruption.'),
        ('Frames ideas in familiar terms rather than technical ones, usually starting from a shared practical point before narrowing into detail. The result is approachable language that still points somewhere concrete.'),
        ('Frames most thoughts in a blunt, usable way, usually putting the main point in the first sentence. Requests come out as practical instructions more often than soft suggestions.'),
        ('Treats exact wording as something that can prevent later trouble, often adding conditions before the main conclusion. The overall effect is deliberate phrasing that reduces misunderstanding by narrowing scope.'),
        ('Uses ordinary phrasing that invites response without losing direction, usually starting from a shared practical point before narrowing into detail. The style is easy to follow because the sentence usually carries both the point and the practical use.'),
        ('States conclusions early and supports them only as needed, usually putting the main point in the first sentence. The style reads as concise without becoming cryptic.'),
        ('Often narrows a statement before defending it, often adding conditions before the main conclusion. The style rewards close reading because the important boundary is usually stated, not assumed.'),
        ('Leans toward natural wording that still carries a clear structure, usually starting from a shared practical point before narrowing into detail. Complex ideas are usually broken into ordinary steps instead of compressed into jargon.'),
        ('Treats wording as a tool rather than a performance, usually putting the main point in the first sentence. Even disagreement is phrased as a correction to the facts instead of a performance of attitude.'),
        ('Organizes speech as if clarity begins with proper framing, often naming the premise before the judgment. The wording favors precision and order over spontaneity.'),
        ('Puts ideas in common terms before adding precision, usually starting from a shared practical point before narrowing into detail. Even corrections tend to arrive as clarifications of the point rather than verbal contests.'),
        ('Favors short, functional phrasing over texture, usually putting the main point in the first sentence. They rarely restate a point unless the first version left room for confusion.'),
        ('Uses a restrained, hedged structure when the facts are incomplete, often adding conditions before the main conclusion. Explanations tend to separate what is known, suspected, and merely possible.'),
        ('Uses deliberate wording that feels considered rather than improvised, often naming the premise before the judgment. Explanations often read like small arguments, with the premises left visible.'),
        ('Keeps the language approachable and easy to enter, usually starting from a shared practical point before narrowing into detail. They rely on plain examples more than abstract wording when a concept could drift.'),
        ('Pushes toward clarity before nuance, usually putting the main point in the first sentence. Details appear only when they help narrow the problem or the next step.'),
        ('Keeps expression tidy and well-shaped, often naming the premise before the judgment. Specific terms are preferred when a looser synonym could blur the point.'),
        ('Favors conversational phrasing that still respects the subject, usually starting from a shared practical point before narrowing into detail. The overall effect is socially easy phrasing with a clear spine underneath it.'),
        ('Uses plain, workmanlike wording, cutting qualifiers unless they change the meaning. Questions are usually framed to get a useful answer rather than invite reflection.'),
        ('Uses careful wording that tries to mark the limits of each claim, using qualifiers to separate fact, guess, and preference. Questions are often used to test assumptions before a full answer is offered.'),
        ('Uses more formal wording than the situation strictly requires, using transitions to show how one thought leads to the next. Even ordinary remarks arrive with a little more structure than casual talk usually carries.'),
        ('Uses friendly, everyday phrasing without getting sloppy, using examples that make the idea feel immediately usable. The wording stays readable because detail is introduced in everyday terms first.'),
        ('Uses wording that breaks problems into parts before drawing a conclusion, comparing options by criteria rather than by mood. Sentences favor structure and comparison over flourish.'),
        ('Keeps the language stripped down and practical, cutting qualifiers unless they change the meaning. When emphasis is needed, they rely on clearer wording instead of stronger ornament.'),
        ('Builds sentences with caution around certainty, using qualifiers to separate fact, guess, and preference. They sound most comfortable when distinctions are named directly instead of implied.'),
        ('Prefers polished phrasing with a clear internal structure, using transitions to show how one thought leads to the next. The result is language that sounds organized without relying on dramatic wording.'),
        ('Builds sentences that feel informal but still organized, using examples that make the idea feel immediately usable. Requests feel collaborative because the sentence often includes the reason for them.'),
        ('Prefers direct statements over decorative phrasing, cutting qualifiers unless they change the meaning. The wording stays literal enough that most listeners know what action is being asked for.'),
        ('Prefers qualified phrasing over hard absolutes, using qualifiers to separate fact, guess, and preference. They prefer to revise a sentence mid-thought rather than let an overbroad version stand.'),
        ('Builds sentences with deliberate order and explicit transitions, using transitions to show how one thought leads to the next. The style is easier to follow because the connective logic is usually stated outright.'),
        ('Prefers language that sounds accessible and unforced, using examples that make the idea feel immediately usable. Statements stay open enough to invite response without becoming vague.'),
        ('Prefers language that sorts causes from effects, comparing options by criteria rather than by mood. Statements often arrive with the standard for judgment attached to them.'),
        ('Frames ideas with conditions before commitment, using qualifiers to separate fact, guess, and preference. Sentences can run a little longer because they carry the limits of the argument with them.'),
        ('Leans toward exact, orderly language, using transitions to show how one thought leads to the next. Questions tend to be fully formed and specific about what answer is being asked for.'),
        ('Keeps wording relaxed while still moving toward a point, using examples that make the idea feel immediately usable. Questions are usually framed to keep the exchange moving instead of stopping it cold.'),
        ('Frames ideas by isolating the moving pieces first, comparing options by criteria rather than by mood. Questions often narrow the frame so the answer can be more exact.'),
        ('Leans on ordinary, concrete words instead of flourish, cutting qualifiers unless they change the meaning. The result is spare language that favors clarity over charm.'),
        ('Chooses language that leaves room for exception, using qualifiers to separate fact, guess, and preference. The wording stays cautious without collapsing into vagueness.'),
        ('Favors complete statements over fragments or shorthand, using transitions to show how one thought leads to the next. When disagreement appears, it is usually framed as a reasoned distinction rather than a sharp interruption.'),
        ('Frames ideas in familiar terms rather than technical ones, using examples that make the idea feel immediately usable. The result is approachable language that still points somewhere concrete.'),
        ('Treats phrasing as a way to map the structure of a problem, comparing options by criteria rather than by mood. The result is language that clarifies relationships between facts instead of merely listing them.'),
        ('Frames most thoughts in a blunt, usable way, cutting qualifiers unless they change the meaning. Requests come out as practical instructions more often than soft suggestions.'),
        ('Treats exact wording as something that can prevent later trouble, using qualifiers to separate fact, guess, and preference. The overall effect is deliberate phrasing that reduces misunderstanding by narrowing scope.'),
        ('Uses ordinary phrasing that invites response without losing direction, using examples that make the idea feel immediately usable. The style is easy to follow because the sentence usually carries both the point and the practical use.'),
        ('Often explains things by separating them into comparable elements, comparing options by criteria rather than by mood. The wording is precise because each sentence is trying to reduce conceptual drift.'),
        ('States conclusions early and supports them only as needed, cutting qualifiers unless they change the meaning. The style reads as concise without becoming cryptic.'),
        ('Often narrows a statement before defending it, using qualifiers to separate fact, guess, and preference. The style rewards close reading because the important boundary is usually stated, not assumed.'),
        ('Leans toward natural wording that still carries a clear structure, using examples that make the idea feel immediately usable. Complex ideas are usually broken into ordinary steps instead of compressed into jargon.'),
        ('Uses clear conceptual boundaries before reaching for judgment, comparing options by criteria rather than by mood. The overall effect is orderly reasoning expressed in plain enough terms to be reusable.'),
        ('Treats wording as a tool rather than a performance, cutting qualifiers unless they change the meaning. Even disagreement is phrased as a correction to the facts instead of a performance of attitude.'),
        ('Approaches speech by defining what is and is not being claimed, using qualifiers to separate fact, guess, and preference. Disagreement usually arrives as a refinement of the premise rather than a flat rejection.'),
        ('Organizes speech as if clarity begins with proper framing, using transitions to show how one thought leads to the next. The wording favors precision and order over spontaneity.'),
        ('Puts ideas in common terms before adding precision, using examples that make the idea feel immediately usable. Even corrections tend to arrive as clarifications of the point rather than verbal contests.'),
        ('Organizes speech by tracing how one factor changes another, comparing options by criteria rather than by mood. When disagreement appears, it usually focuses on the setup of the argument rather than the surface wording alone.'),
        ('Favors short, functional phrasing over texture, cutting qualifiers unless they change the meaning. They rarely restate a point unless the first version left room for confusion.'),
        ('Uses a restrained, hedged structure when the facts are incomplete, using qualifiers to separate fact, guess, and preference. Explanations tend to separate what is known, suspected, and merely possible.'),
        ('Uses deliberate wording that feels considered rather than improvised, using transitions to show how one thought leads to the next. Explanations often read like small arguments, with the premises left visible.'),
        ('Keeps the language approachable and easy to enter, using examples that make the idea feel immediately usable. They rely on plain examples more than abstract wording when a concept could drift.'),
        ('Pushes toward clarity before nuance, cutting qualifiers unless they change the meaning. Details appear only when they help narrow the problem or the next step.'),
        ('Keeps claims measured and deliberately bounded, using qualifiers to separate fact, guess, and preference. Requests are often framed with the constraint attached so the expectation stays realistic.'),
        ('Keeps expression tidy and well-shaped, using transitions to show how one thought leads to the next. Specific terms are preferred when a looser synonym could blur the point.'),
        ('Favors conversational phrasing that still respects the subject, using examples that make the idea feel immediately usable. The overall effect is socially easy phrasing with a clear spine underneath it.'),
        ('Uses structured wording to make relationships between ideas visible, comparing options by criteria rather than by mood. The style reads as methodical without requiring technical jargon.'),
        ('Uses plain, workmanlike wording, keeping examples short and attached to the immediate topic. Questions are usually framed to get a useful answer rather than invite reflection.'),
        ('Uses careful wording that tries to mark the limits of each claim, explaining the exception before the rule when it matters. Questions are often used to test assumptions before a full answer is offered.'),
        ('Uses more formal wording than the situation strictly requires, preferring full statements over implication when the stakes matter. Even ordinary remarks arrive with a little more structure than casual talk usually carries.'),
        ('Uses friendly, everyday phrasing without getting sloppy, letting a sentence unfold in a natural order before landing the main point. The wording stays readable because detail is introduced in everyday terms first.'),
        ('Uses wording that breaks problems into parts before drawing a conclusion, separating observation from interpretation inside the same answer. Sentences favor structure and comparison over flourish.'),
        ('Keeps the language stripped down and practical, keeping examples short and attached to the immediate topic. When emphasis is needed, they rely on clearer wording instead of stronger ornament.'),
        ('Builds sentences with caution around certainty, explaining the exception before the rule when it matters. They sound most comfortable when distinctions are named directly instead of implied.'),
        ('Prefers polished phrasing with a clear internal structure, preferring full statements over implication when the stakes matter. The result is language that sounds organized without relying on dramatic wording.'),
        ('Builds sentences that feel informal but still organized, letting a sentence unfold in a natural order before landing the main point. Requests feel collaborative because the sentence often includes the reason for them.'),
        ('Prefers direct statements over decorative phrasing, keeping examples short and attached to the immediate topic. The wording stays literal enough that most listeners know what action is being asked for.')
), normalized AS (
    SELECT DISTINCT TRIM(description) AS description
    FROM source_rows
    WHERE TRIM(description) <> ''
)
INSERT INTO bio_random (type, description, name, race, gender, faction)
SELECT 'speechstyle', n.description, '', '', '', ''
FROM normalized n
ON CONFLICT (type, description, name) DO NOTHING;
COMMIT;
