<?php $isEmbed = strval($_GET['embed'] ?? '') === '1'; ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>STT Test</title><link rel="stylesheet" href="css/main.css"><style>body{padding:<?= $isEmbed ? '14px' : '85px 14px' ?>;background:#2c2c2c}.box{max-width:720px;margin:auto;background:#242424;border:1px solid #444;border-radius:9px;padding:18px}.box h1{color:#e6b76c}.box button{padding:10px 14px;border-radius:7px;border:1px solid #53617a;background:#2f3b52;color:#fff}.box button.recording{background:#8f2836}.result{white-space:pre-wrap;margin-top:15px;color:#dbe4f4}</style></head><body>
<?php if(!$isEmbed) include __DIR__.'/tmpl/navbar.php'; ?>
<main class="box"><h1>Microphone Test</h1><p>Press record, speak, then stop to test the active Stobe STT connector.</p><button id="record">Start Recording</button><div id="result" class="result"></div></main>
<script>
let context,source,processor,stream,buffers=[],sampleRate=16000;const button=document.getElementById('record'),output=document.getElementById('result');
function wavBlob(samples,rate){const b=new ArrayBuffer(44+samples.length*2),v=new DataView(b),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+samples.length*2,true);w(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,samples.length*2,true);for(let i=0;i<samples.length;i++)v.setInt16(44+i*2,Math.max(-1,Math.min(1,samples[i]))*32767,true);return new Blob([b],{type:'audio/wav'})}
function resample(input,from,to){if(from===to)return input;const size=Math.round(input.length*to/from),out=new Float32Array(size);for(let i=0;i<size;i++){const p=i*from/to,a=Math.floor(p),f=p-a;out[i]=(input[a]||0)*(1-f)+(input[Math.min(a+1,input.length-1)]||0)*f}return out}
async function stop(){processor.disconnect();source.disconnect();stream.getTracks().forEach(t=>t.stop());await context.close();const total=buffers.reduce((n,b)=>n+b.length,0),joined=new Float32Array(total);let at=0;buffers.forEach(b=>{joined.set(b,at);at+=b.length});button.textContent='Start Recording';button.classList.remove('recording');output.textContent='Transcribing...';const fd=new FormData();fd.append('file',wavBlob(resample(joined,context.sampleRate,sampleRate),sampleRate),'microphone.wav');try{const r=await fetch('../stt.php',{method:'POST',body:fd}),j=await r.json();output.textContent=j.ok?j.text:(j.error||'Transcription failed.')}catch(e){output.textContent='Transcription failed: '+e.message}context=null}
button.onclick=async()=>{if(context){await stop();return}try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true}});context=new AudioContext();source=context.createMediaStreamSource(stream);processor=context.createScriptProcessor(4096,1,1);buffers=[];processor.onaudioprocess=e=>buffers.push(new Float32Array(e.inputBuffer.getChannelData(0)));source.connect(processor);processor.connect(context.destination);button.textContent='Stop Recording';button.classList.add('recording');output.textContent='Recording...'}catch(e){output.textContent='Microphone access failed: '+e.message;context=null}};
</script></body></html>
